### ISSUE TITLE
NoSuchFieldError: REQUIREMENTS

### ISSUE THREAD

**Issue by kumarivin** [toliwa/CoreNLP-jMWE#1]
After following all the instructions, I am getting the below  error when trying to run this extension. 
> Adding annotator jmwe
Exception in thread "main" java.lang.NoSuchFieldError: REQUIREMENTS
	at edu.stanford.nlp.pipeline.JMWEAnnotator.requires(JMWEAnnotator.java:137)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:293)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:126)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:122)
	at com.clearcut.nlp.DocumentParser.<init>(DocumentParser.scala:15)
	at com.clearcut.nlp.Main$delayedInit$body.apply(Main.scala:79)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.clearcut.nlp.Main$.main(Main.scala:10)
	at com.clearcut.nlp.Main.main(Main.scala)

**Comment by toltoxgh** [comment]
I just updated CoreNLP-jMWE to be compatible with Stanford CoreNLP 3.7.0, the latest stable version as of right now. Use the current version of CoreNLP-jMWE from its master branch, and run all tests to make sure all is setup correctly.

**Comment by toltoxgh** [comment]
Resolved. Closing issue.
